import type { AdminTranslations } from "./en";

export const adminLv: AdminTranslations = {
  sidebar: { title: "Vesper Admin", dashboard: "Panelis", brands: "Zīmoli", products: "Produkti", news: "Ziņas", categories: "Kategorijas", backToSite: "Atpakaļ uz mājaslapu", settings: "Iestatījumi", darkMode: "Tumšais režīms", lightMode: "Gaišais režīms", auditLog: "Darbību žurnāls" },
  dashboard: { title: "Vadības panelis", subtitle: "Satura pārskats un analītika", totalBrands: "Zīmoli kopā", totalProducts: "Produkti kopā", totalNews: "Ziņu raksti", totalCategories: "Kategorijas", recentActivity: "Pēdējās darbības", quickActions: "Ātrās darbības", addBrand: "Pievienot zīmolu", addProduct: "Pievienot produktu", addArticle: "Pievienot rakstu", addCategory: "Pievienot kategoriju", stubWarning: "API darbojas testa režīmā", stubDesc: "Dati tiek glabāti atmiņā un pazūd, pārlādējot lapu. Pieslēdziet Lovable Cloud, lai dati saglabātos pastāvīgi.", welcome: "Laipni lūdzam atpakaļ", todayDate: "Šodien", contentBreakdown: "Satura sadalījums", systemStatus: "Sistēmas statuss", statusOnline: "Tiešsaistē", statusStub: "Testa režīms", database: "Datubāze", storage: "Krātuve", auth: "Autentifikācija", notConnected: "Nav pieslēgts", connectCloud: "Pieslēgt Cloud", exportData: "Eksportēt datus", viewAll: "Skatīt visu", pageViews: "Lapu skatījumi", topPages: "Populārākās lapas", views: "skatījumi", trend: "tendence" },
  common: { create: "Izveidot", save: "Saglabāt", cancel: "Atcelt", delete: "Dzēst", edit: "Rediģēt", search: "Meklēt…", noData: "Dati nav atrasti", loading: "Ielādē…", actions: "Darbības", confirmDelete: "Vai tiešām vēlaties dzēst", required: "Obligāts lauks", name: "Nosaukums", description: "Apraksts", category: "Kategorija", country: "Valsts", year: "Gads", logoUrl: "Logotipa URL", imageUrl: "Attēla URL", items: "ieraksti", all: "Visi", filters: "Filtri", export: "Eksportēt CSV", duplicate: "Dublēt", preview: "Priekšskatījums", selected: "atlasīti", bulkDelete: "Dzēst atlasītos", selectAll: "Atlasīt visu", deselectAll: "Noņemt atlasi", sortBy: "Kārtot pēc", ascending: "Augoši", descending: "Dilstoši", showing: "Rāda", of: "no", perPage: "lapā", previous: "Iepriekšējā", next: "Nākamā", close: "Aizvērt", details: "Detaļas", status: "Statuss", active: "Aktīvs", draft: "Melnraksts", lastModified: "Pēdējās izmaiņas", createdAt: "Izveidots", reorder: "Velciet, lai pārkārtotu", image: "Attēls", uploadImage: "Augšupielādēt attēlu", orEnterUrl: "vai ievadiet URL", emailSent: "Paziņojums nosūtīts", emailFailed: "Paziņojumu neizdevās nosūtīt" },
  brands: { title: "Zīmoli", subtitle: "Pārvaldiet savus dzērienu zīmolus", addBrand: "Pievienot zīmolu", editBrand: "Rediģēt zīmolu", newBrand: "Jauns zīmols", nameRequired: "Nosaukums ir obligāts", brandCreated: "Zīmols izveidots", brandUpdated: "Zīmols atjaunināts", brandDeleted: "Zīmols izdzēsts", productsCount: "Produkti", viewProducts: "Skatīt produktus", duplicated: "Zīmols dublēts", reorderMode: "Pārkārtot", reorderDone: "Gatavs", orderSaved: "Secība saglabāta" },
  products: { title: "Produkti", subtitle: "Pārvaldiet visu zīmolu produktus", addProduct: "Pievienot produktu", editProduct: "Rediģēt produktu", newProduct: "Jauns produkts", selectBrand: "Izvēlieties zīmolu", brand: "Zīmols", type: "Veids", volume: "Tilpums", abv: "Spirta saturs", shopUrl: "Veikala saite", nameRequired: "Nosaukums ir obligāts", brandRequired: "Lūdzu, izvēlieties zīmolu", productCreated: "Produkts izveidots", productUpdated: "Produkts atjaunināts", productDeleted: "Produkts izdzēsts", allBrands: "Visi zīmoli", allTypes: "Visi veidi", duplicated: "Produkts dublēts" },
  news: { title: "Ziņas", subtitle: "Pārvaldiet ziņu rakstus un jaunumus", addArticle: "Pievienot rakstu", editArticle: "Rediģēt rakstu", newArticle: "Jauns raksts", articleTitle: "Virsraksts", slug: "Slug", excerpt: "Kopsavilkums", content: "Saturs", date: "Datums", titleRequired: "Virsraksts ir obligāts", slugRequired: "Slug ir obligāts", articleCreated: "Raksts izveidots", articleUpdated: "Raksts atjaunināts", articleDeleted: "Raksts izdzēsts", published: "Publicēts", draft: "Melnraksts", previewArticle: "Priekšskatīt mājaslapā", duplicated: "Raksts dublēts", generateSlug: "Ģenerēt no virsraksta", markdown: "Markdown", multilang: "Daudzvalodu" },
  categories: { title: "Kategorijas", subtitle: "Organizējiet produktu kategorijas", addCategory: "Pievienot kategoriju", editCategory: "Rediģēt kategoriju", newCategory: "Jauna kategorija", slug: "Slug", slugAuto: "automātiski ģenerēts", brandsCount: "Zīmoli", nameRequired: "Nosaukums ir obligāts", categoryCreated: "Kategorija izveidota", categoryUpdated: "Kategorija atjaunināta", categoryDeleted: "Kategorija izdzēsta", duplicated: "Kategorija dublēta", reorderMode: "Pārkārtot", reorderDone: "Gatavs", orderSaved: "Secība saglabāta" },
  audit: { title: "Darbību žurnāls", subtitle: "Sekojiet visām izmaiņām un darbībām", noActivity: "Pagaidām nav darbību", created: "izveidoja", updated: "atjaunināja", deleted: "izdzēsa", brand: "Zīmols", product: "Produkts", news: "Raksts", category: "Kategorija" },
};
