import type { AdminTranslations } from "./en";

export const adminRu: AdminTranslations = {
  sidebar: { title: "Vesper Admin", dashboard: "Обзор", brands: "Бренды", products: "Продукты", news: "Новости", categories: "Категории", backToSite: "На сайт", settings: "Настройки", darkMode: "Тёмная тема", lightMode: "Светлая тема", auditLog: "Журнал действий" },
  dashboard: { title: "Панель управления", subtitle: "Аналитика и обзор контента", totalBrands: "Всего брендов", totalProducts: "Всего продуктов", totalNews: "Новостей", totalCategories: "Категорий", recentActivity: "Последняя активность", quickActions: "Быстрые действия", addBrand: "Добавить бренд", addProduct: "Добавить продукт", addArticle: "Добавить статью", addCategory: "Добавить категорию", stubWarning: "API в режиме заглушек", stubDesc: "Данные хранятся в памяти и сбрасываются при перезагрузке. Подключите Lovable Cloud для постоянного хранения, авторизации и загрузки файлов.", welcome: "С возвращением", todayDate: "Сегодня", contentBreakdown: "Разбивка контента", systemStatus: "Статус системы", statusOnline: "Онлайн", statusStub: "Режим заглушек", database: "База данных", storage: "Хранилище", auth: "Авторизация", notConnected: "Не подключено", connectCloud: "Подключить Cloud", exportData: "Экспорт данных", viewAll: "Смотреть все", pageViews: "Просмотры страниц", topPages: "Популярные страницы", views: "просмотров", trend: "тренд" },
  common: { create: "Создать", save: "Сохранить", cancel: "Отмена", delete: "Удалить", edit: "Редактировать", search: "Поиск…", noData: "Нет данных", loading: "Загрузка…", actions: "Действия", confirmDelete: "Вы уверены что хотите удалить", required: "Обязательно", name: "Название", description: "Описание", category: "Категория", country: "Страна", year: "Год", logoUrl: "URL логотипа", imageUrl: "URL изображения", items: "записей", all: "Все", filters: "Фильтры", export: "Экспорт CSV", duplicate: "Дублировать", preview: "Предпросмотр", selected: "выбрано", bulkDelete: "Удалить выбранные", selectAll: "Выбрать все", deselectAll: "Снять выбор", sortBy: "Сортировать по", ascending: "По возрастанию", descending: "По убыванию", showing: "Показано", of: "из", perPage: "на странице", previous: "Назад", next: "Далее", close: "Закрыть", details: "Детали", status: "Статус", active: "Активный", draft: "Черновик", lastModified: "Изменён", createdAt: "Создан", reorder: "Перетащите для сортировки", image: "Изображение", uploadImage: "Загрузить изображение", orEnterUrl: "или введите URL", emailSent: "Уведомление отправлено", emailFailed: "Не удалось отправить уведомление" },
  brands: { title: "Бренды", subtitle: "Управление брендами напитков", addBrand: "Добавить бренд", editBrand: "Редактировать бренд", newBrand: "Новый бренд", nameRequired: "Название обязательно", brandCreated: "Бренд создан", brandUpdated: "Бренд обновлён", brandDeleted: "Бренд удалён", productsCount: "Продуктов", viewProducts: "Смотреть продукты", duplicated: "Бренд дублирован", reorderMode: "Сортировка", reorderDone: "Готово", orderSaved: "Порядок сохранён" },
  products: { title: "Продукты", subtitle: "Управление продуктами всех брендов", addProduct: "Добавить продукт", editProduct: "Редактировать продукт", newProduct: "Новый продукт", selectBrand: "Выберите бренд", brand: "Бренд", type: "Тип", volume: "Объём", abv: "Крепость", shopUrl: "URL магазина", nameRequired: "Название обязательно", brandRequired: "Выберите бренд", productCreated: "Продукт создан", productUpdated: "Продукт обновлён", productDeleted: "Продукт удалён", allBrands: "Все бренды", allTypes: "Все типы", duplicated: "Продукт дублирован" },
  news: { title: "Новости", subtitle: "Управление новостными статьями", addArticle: "Добавить статью", editArticle: "Редактировать статью", newArticle: "Новая статья", articleTitle: "Заголовок", slug: "Slug", excerpt: "Краткое описание", content: "Содержание", date: "Дата", titleRequired: "Заголовок обязателен", slugRequired: "Slug обязателен", articleCreated: "Статья создана", articleUpdated: "Статья обновлена", articleDeleted: "Статья удалена", published: "Опубликовано", draft: "Черновик", previewArticle: "Предпросмотр на сайте", duplicated: "Статья дублирована", generateSlug: "Сгенерировать из заголовка", markdown: "Markdown", multilang: "Мультиязычный" },
  categories: { title: "Категории", subtitle: "Организация категорий продуктов", addCategory: "Добавить категорию", editCategory: "Редактировать категорию", newCategory: "Новая категория", slug: "Slug", slugAuto: "автоматически", brandsCount: "Брендов", nameRequired: "Название обязательно", categoryCreated: "Категория создана", categoryUpdated: "Категория обновлена", categoryDeleted: "Категория удалена", duplicated: "Категория дублирована", reorderMode: "Сортировка", reorderDone: "Готово", orderSaved: "Порядок сохранён" },
  audit: { title: "Журнал действий", subtitle: "Отслеживание всех изменений", noActivity: "Пока нет действий", created: "создал(а)", updated: "обновил(а)", deleted: "удалил(а)", brand: "Бренд", product: "Продукт", news: "Статья", category: "Категория" },
};
